@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package alpvax.advancedautocrafting.api.wire;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;