@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package alpvax.advancedautocrafting.client.model;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;