@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package alpvax.advancedautocrafting.inventory;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;