@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package alpvax.advancedautocrafting.block.wire.parts;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;