@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package alpvax.advancedautocrafting.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;